_wandb:
    value:
        cli_version: 0.23.1
        e:
            jk38sdk01ib18j1s03rp07w8somx3b1i:
                args:
                    - --run_sft
                    - --run_inf
                codePath: Ass4-LLM/src/main_CPT_SFT.py
                codePathLocal: main_CPT_SFT.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "502392610816"
                        used: "53266649088"
                email: benten.hsu@gmail.com
                executable: /home/ben/miniconda3/envs/Ass4/bin/python
                git:
                    commit: 269f6b0bddee2ff46f478963e81a4be89ea41dd5
                    remote: https://github.com/benhsu0828/NYCU_IAII_ML2025.git
                gpu: NVIDIA Graphics Device
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 2560
                      memoryTotal: "8546942976"
                      name: NVIDIA Graphics Device
                      uuid: GPU-b1c0431a-cc1f-6517-7e5a-48d0573e4eff
                host: ben-LAB
                memory:
                    total: "15936311296"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /home/ben/桌面/NYCU_IAII_ML2025/Ass4-LLM/src/./main_CPT_SFT.py
                python: CPython 3.11.14
                root: /home/ben/桌面/NYCU_IAII_ML2025/Ass4-LLM/src
                startedAt: "2025-12-11T11:15:34.796771Z"
                writerId: jk38sdk01ib18j1s03rp07w8somx3b1i
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 13
                - 15
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": linux-x86_64
base_model:
    value: ./model/cpt_model
batch_size:
    value: 1
gradient_accumulation:
    value: 16
learning_rate:
    value: 1e-05
lora_alpha:
    value: 32
lora_r:
    value: 16
max_seq_length:
    value: 1024
max_steps:
    value: 100
stage:
    value: SFT
vram:
    value: 8GB
